latest release
Signed-off-by: sownak <sownak.roy@accenture.com>

diff --git a/examples/dscp-app/charts/dscp-chain-watcher/templates/cronjob.yaml b/examples/dscp-app/charts/dscp-chain-watcher/templates/cronjob.yaml
--- a/examples/dscp-app/charts/dscp-chain-watcher/templates/cronjob.yaml
+++ b/examples/dscp-app/charts/dscp-chain-watcher/templates/cronjob.yaml
@@ -23,43 +23,135 @@ spec:
           restartPolicy: OnFailure
           securityContext:
             fsGroup: 1000
+          serviceAccountName: {{ .Values.vault.serviceaccountname }} 
+          {{- if .Values.vault.createInitContainer }}     
+          initContainers:
+            - name: vault-init
+              image: {{ .Values.vault.alpineutils }}
+              imagePullPolicy: Always
+              volumeMounts:
+              - name: config
+                mountPath: /secret
+              env:
+              - name: VAULT_ADDR
+                value: {{ .Values.vault.address }}
+              - name: VAULT_SECRET_PREFIX
+                value: {{ .Values.vault.secretprefix }}
+              - name: KUBERNETES_AUTH_PATH
+                value: {{ .Values.vault.authpath }}
+              - name: VAULT_APP_ROLE
+                value: {{ .Values.vault.role }}
+              - name: MOUNT_PATH
+                value: "/secret"
+              command: ["sh", "-c"]
+              args:
+              - |-
+                #!/usr/bin/env sh
+                validateVaultResponse () {
+                    if echo ${2} | grep "errors"; then
+                      echo "ERROR: unable to retrieve ${1}: ${2}"
+                      exit 1
+                    fi
+                    if  [ "$3" == "LOOKUPSECRETRESPONSE" ]
+                    then
+                      http_code=$(curl -sS -o /dev/null -w "%{http_code}" \
+                      --header "X-Vault-Token: ${VAULT_CLIENT_TOKEN}" \
+                      ${VAULT_ADDR}/v1/${vault_secret_key})
+                      curl_response=$?
+                      if test "$http_code" != "200" ; then
+                          echo "Http response code from Vault - $http_code"
+                          if test "$curl_response" != "0"; then
+                            echo "Error: curl command failed with error code - $curl_response"
+                            exit 1
+                          fi
+                      fi
+                    fi
+                  }
+                  KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
+                  echo "Getting secrets from Vault Server: ${VAULT_ADDR}"
+
+                  #Login to Vault and so I can get an approle token
+                  VAULT_CLIENT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login \
+                    -H "Content-Type: application/json" \
+                    -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | \
+                    jq -r 'if .errors then . else .auth.client_token end')
+                  validateVaultResponse 'vault login token' "${VAULT_CLIENT_TOKEN}"
+                  echo "Logged into Vault"
+      
+                  vault_secret_key="${VAULT_SECRET_PREFIX}/gcpkey"
+
+                  echo "Getting the gcp key from vault: $vault_secret_key"          
+                  LOOKUP_SECRET_RESPONSE=$(curl -sS \
+                    --header "X-Vault-Token:${VAULT_CLIENT_TOKEN}" \
+                    ${VAULT_ADDR}/v1/${vault_secret_key} | \
+                    jq -r 'if .errors then . else . end')
+                  validateVaultResponse "secret (${vault_secret_key})" "${LOOKUP_SECRET_RESPONSE}" "LOOKUPSECRETRESPONSE"
+                  gcpKey=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data.data["gcpkey"]')
+                                
+                  echo -n "${gcpKey}" > ${MOUNT_PATH}/gcpKey.json
+          {{- end }}
           containers:
-          - name: {{ include "chain-watcher.fullname" . }}-cron-job
-            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
-            imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
-            env:
-              - name: DB_HOST
-                valueFrom:
-                  configMapKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-config
-                    key: dbHost
-              - name: DB_PORT
-                valueFrom:
-                  configMapKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-config
-                    key: dbPort
-              - name: DB_NAME
-                valueFrom:
-                  configMapKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-config
-                    key: dbName
-              - name: DSCP_API_HOST
-                valueFrom:
-                  configMapKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-config
-                    key: dscpApiHost
-              - name: DSCP_API_PORT
-                valueFrom:
-                  configMapKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-config
-                    key: dscpApiPort
-              - name: DB_USERNAME
-                valueFrom:
-                  secretKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-secret
-                    key: dbUsername
-              - name: DB_PASSWORD
-                valueFrom:
-                  secretKeyRef:
-                    name: {{ include "chain-watcher.fullname" . }}-secret
-                    key: dbPassword
+            - name: {{ include "chain-watcher.fullname" . }}-cron-job
+              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
+              imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
+              volumeMounts:
+              - name: config
+                mountPath: /secret
+              command: ["sh", "-c"]
+              args:
+              - |-
+                #!/usr/bin/env sh
+
+                export GOOGLE_APPLICATION_CREDENTIALS=/secret/gcpKey.json
+
+                node ./index.js
+              env:
+                - name: DB_HOST
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: dbHost
+                - name: DB_PORT
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: dbPort
+                - name: DB_NAME
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: dbName
+                - name: DSCP_API_HOST
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: dscpApiHost
+                - name: DSCP_API_PORT
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: dscpApiPort
+                - name: DB_USERNAME
+                  valueFrom:
+                    secretKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-secret
+                      key: dbUsername
+                - name: DB_PASSWORD
+                  valueFrom:
+                    secretKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-secret
+                      key: dbPassword
+                - name: IDENTITY_SERVICE_HOST
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: idServiceHost
+                - name: IDENTITY_SERVICE_PORT
+                  valueFrom:
+                    configMapKeyRef:
+                      name: {{ include "chain-watcher.fullname" . }}-config
+                      key: idServicePort
+          volumes:
+            - name: config
+              emptyDir:
+                medium: Memory
